#index:
#    path: /
#    controller: App\Controller\DefaultController::index
user:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template: 'user.html.twig'

answer:
    path: /answer
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template: 'submitexam.html.twig'
quizadd:
    path: /quizadd
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template: 'quizadd.html.twig'

teacher:
    path: /teacher
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template: 'teacher.html.twig'

app_mail:
    path: /mail
    controller: App\Controller\mailcontroller::mail
student:
    path: /student
    controller: App\Controller\StudentController::student

quiz:
    path: /quiz1
    controller: App\Controller\QuizController::quiz
    defaults:

quiz2:
    path: /quiz2
    controller: App\Controller\QuizController::quiz2
    defaults:
quiz3:
    path: /quiz3
    controller: App\Controller\QuizController::quiz3
    defaults:

quiz4:
    path: /quiz4
    controller: App\Controller\QuizController::quiz4
    defaults:
