#index:
#    path: /
#    controller: App\Controller\DefaultController::index
user:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template: 'user.html.twig'

quiz:
    path: /quiz
    controller: App\Controller\Quizcontroller::quiz

teacher:
    path: /teacher
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template: 'teacher.html.twig'

app_mail:
    path: /mail
    controller: App\Controller\mailcontroller::mail
student:
    path: /student
    controller: App\Controller\Studentcontroller::student
