#index:
#    path: /
#    controller: App\Controller\DefaultController::index
user:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template: 'user.html.twig'

teacher:
    path: /teacher
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template: 'teacher.html.twig'

student:
    path: /student
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template: 'student.html.twig'
