#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_lucky_number:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template: 'home_page.html.twig'
