<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\Quiz2Controller' shared autowired service.

include_once $this->targetDirs[3].'\\src\\Controller\\Quiz2Controller.php';

return $this->services['App\Controller\Quiz2Controller'] = new \App\Controller\Quiz2Controller();
