<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXLJXv0c\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXLJXv0c/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerXLJXv0c.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerXLJXv0c\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerXLJXv0c\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'XLJXv0c',
    'container.build_id' => 'a04d30c8',
    'container.build_time' => 1539175334,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerXLJXv0c');
