<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHhHcT3u\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHhHcT3u/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHhHcT3u.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHhHcT3u\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerHhHcT3u\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'HhHcT3u',
    'container.build_id' => 'a2f30080',
    'container.build_time' => 1539432527,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerHhHcT3u');
