<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container63eYJWA\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container63eYJWA/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container63eYJWA.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container63eYJWA\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container63eYJWA\srcDevDebugProjectContainer(array(
    'container.build_hash' => '63eYJWA',
    'container.build_id' => '2f0dcdeb',
    'container.build_time' => 1539238896,
), __DIR__.\DIRECTORY_SEPARATOR.'Container63eYJWA');
